### ISSUE TITLE
Unresponsive UI and problem with larger files

### ISSUE THREAD

**Issue by rabinxyz** [wbstr/vaadin-multifileupload#15]
Hi 

   I have similar problems as described here: https://github.com/wbstr/vaadin-multifileupload/issues/10

My configuration: Multiupload: 1.8, Vaadin 7.2.1, Push configuration: AUTOMATIC/WEBSOCKET

Larger files (bigger than around 5 MB). Dialog is not shown, vaadin indicator is not inform about any request, but uploading is handled in background. When I try to refresh page I'm getting information about upload cancellation.

For smaller files dialogs shows but sometimes is not responsive, sometimes it takes some time to show, and sometimes it's not hidden after upload is finish.

Do You have maybe some advice in this case?

**Comment by juger89** [comment]
#17 will give a "solution" for this.
