### ISSUE TITLE
Content length == 0

### ISSUE THREAD

**Issue by rabinxyz** [wbstr/vaadin-multifileupload#16]
![zrzut ekranu 2014-06-10 o 13 02 22](https://cloud.githubusercontent.com/assets/1948757/3229002/dc2c3b98-f08e-11e3-83fc-448634c4bde1.png)
Hi 

   I have issue for single file upload. UploadFinishHandler -> handleFile methtods provides content length parameter == 0.

My configuration: Multiupload: 1.8, Vaadin 7.2.1, Push configuration: AUTOMATIC/WEBSOCKET

Regards
Sebastian

**Comment by juger89** [comment]
Fixed in 1.10.
