### ISSUE TITLE
intercept the end of a multiple upload batch

### ISSUE THREAD

**Issue by goingwip** [wbstr/vaadin-multifileupload#24]
Hi, 
thank you very much for great add-on!
As asked here in a comment already: https://vaadin.com/directory#!addon/multifileupload I would also ask you if this feature could be implemented: "It would be useful to have a way to intercept the end of a multiple upload batch." 
On this way I'd get a chance to en-/disable a button to start the forwarding of all uploaded (kinda cached) files further way to a third system.
Thank you!
Roman.

**Comment by juger89** [comment]
Fixed in 1.10.
`multiFileUpload.setAllUploadFinishedHandler(AllUploadFinishedHandler allUploadFinishedHandler) `
