### ISSUE TITLE
set focus on button

### ISSUE THREAD

**Issue by jodoming** [wbstr/vaadin-multifileupload#25]
Hi,
I´m locking for the possibility to set the focus on the button of the uploadcomponent.
I know that the simply set of the focus to the MultiFileUpload component is not the solution because it is a custom component. 
I had a look at the client components (VMultiUpload, VCustomUpload) and haven´t seen any solution of focusing concerning the included VButton inside the client components.

Can you help me?

**Comment by juger89** [comment]
Fixed in 1.10.
You can also set tabindexes.
