### ISSUE TITLE
can't upload the same file if it's canceled before 

### ISSUE THREAD

**Issue by rjwuqq** [wbstr/vaadin-multifileupload#31]
Hi,
There is an issue for the cancel upload process.
the maxFileSize limit is set to 1G and the upload file used to upload is about 700M
int maxFileSize = 5242880*200; //1G
Steps for reproduce:
1. select one file for uploading
2. when uploading status panel window appear, cancel it
3. select the same file uploading again
4. nothing the upload widget will do 
This issue occurs on chrome/edge, but not on firefox
Vaadin: 7.5.9 and above
Chrome:  48.0.2564.116 m
OS: Windows 10

**Comment by rjwuqq** [comment]
the maxFileSize limit is set to 1G
int maxFileSize = 5242880*200; //1G

**Comment by juger89** [comment]
Browser event in Chrome become ONFOCUS instead of ONCHANGE if selecting the same files as before, so the input won't submitted. To avoid this problem, I've set input value to null after files have been submitted.
