### ISSUE TITLE
No server synchronization after single file upload for multiple mode

### ISSUE THREAD

**Issue by bgeagle** [wbstr/vaadin-multifileupload#33]
In multiple mode there is no synchronization with server side after finishing upload of single file (only a one file is choosen for upload). When more files are uploaded (2 or more chosen files) synchronization is made correctly.

Tested for Vaadin 7.6.4 and 7.6.3.

**Comment by juger89** [comment]
I think it's the same problem as described in #31 and #35. Please check the new version after release.
