### ISSUE TITLE
Cancel button outside grid

### ISSUE THREAD

**Issue by spostma73** [wbstr/vaadin-multifileupload#40]
The cancel button is halfway outside the grid:
![image](https://cloud.githubusercontent.com/assets/5493812/20072104/47ac01a6-a50e-11e6-9a8a-da7ab63f67ed.png)
This is using the default valo theme.

**Comment by juger89** [comment]
Check version 2.0.3. 
Demo is using Valo theme:
http://demo.webstar.hu/multifileupload/
