### ISSUE TITLE
IllegalStateException on setReadOnly

### ISSUE THREAD

**Issue by kumm** [wbstr/vaadin-multifileupload#46]
Due to a change in vaadin8.

stacktrace:
java.lang.IllegalStateException: This component does not support the read-only mode, since state is of type CustomComponentState and does not inherit AbstractFieldState
	at com.vaadin.ui.AbstractComponent.setReadOnly(AbstractComponent.java:1082)
	at com.wcs.wcslib.vaadin.widget.multifileupload.ui.MultiFileUpload.setReadOnly(MultiFileUpload.java:224)

**Comment by kumm** [comment]
https://vaadin.com/download/prerelease/8.0/8.0.0/8.0.0.beta1/release-notes.html#incompatible
"Read-only is now a feature for field components and has been moved from AbstractComponent to HasValue"

**Comment by Hedath** [comment]
Fixed in 3.0.1.
